export type KitchenCategory = 
  | "dairy" 
  | "meat" 
  | "veg" 
  | "fruit" 
  | "bakery" 
  | "dry" 
  | "frozen" 
  | "drinks" 
  | "sweets"
  | "other";

export interface ProductSuggestion {
  name: string;
  category: KitchenCategory;
}

export const PRODUCT_DICTIONARY: ProductSuggestion[] = [
  // Dairy (Piena produkti un alternatīvas)
  { name: "Olas", category: "dairy" },
  { name: "Piens", category: "dairy" },
  { name: "Siers", category: "dairy" },
  { name: "Biezpiens", category: "dairy" },
  { name: "Sviests", category: "dairy" },
  { name: "Krējums", category: "dairy" },
  { name: "Jogurts", category: "dairy" },
  { name: "Kefīrs", category: "dairy" },
  { name: "Grieķu jogurts", category: "dairy" },
  { name: "Mozzarella", category: "dairy" },
  { name: "Parmas siers", category: "dairy" },
  { name: "Feta", category: "dairy" },
  { name: "Čedaras siers", category: "dairy" },
  { name: "Gouda siers", category: "dairy" },
  { name: "Zilais siers", category: "dairy" },
  { name: "Siers Brie", category: "dairy" },
  { name: "Siers Camembert", category: "dairy" },
  { name: "Mascarpone", category: "dairy" },
  { name: "Ricotta", category: "dairy" },
  { name: "Halloumi siers", category: "dairy" },
  { name: "Kausētais siers", category: "dairy" },
  { name: "Mandeļu piens", category: "dairy" },
  { name: "Auzu piens", category: "dairy" },
  { name: "Kokosriekstu piens", category: "dairy" },
  { name: "Sojas piens", category: "dairy" },
  { name: "Rīsu piens", category: "dairy" },
  { name: "Gī sviests", category: "dairy" },
  { name: "Mandeļu jogurts", category: "dairy" },
  { name: "Kokosriekstu krējums", category: "dairy" },
  { name: "Augu krējums", category: "dairy" },
  { name: "Tofu (stingrais)", category: "dairy" },
  { name: "Tofu (mīkstais)", category: "dairy" },
  
  // Meat & Fish (Gaļa un zivis)
  { name: "Vistas fileja", category: "meat" },
  { name: "Vistas stilbiņi", category: "meat" },
  { name: "Vistas spārniņi", category: "meat" },
  { name: "Cūkgaļa", category: "meat" },
  { name: "Cūkgaļas karbonāde", category: "meat" },
  { name: "Cūkgaļas krūtiņa", category: "meat" },
  { name: "Liellopa gaļa", category: "meat" },
  { name: "Liellopa steiks", category: "meat" },
  { name: "Malta gaļa", category: "meat" },
  { name: "Tītaru gaļa", category: "meat" },
  { name: "Pīles gaļa", category: "meat" },
  { name: "Jēra gaļa", category: "meat" },
  { name: "Lasis", category: "meat" },
  { name: "Laša fileja", category: "meat" },
  { name: "Forele", category: "meat" },
  { name: "Tuncis", category: "meat" },
  { name: "Konservēts tuncis", category: "meat" },
  { name: "Garneles", category: "meat" },
  { name: "Mīdijas", category: "meat" },
  { name: "Kalmāri", category: "meat" },
  { name: "Astoņkājis", category: "meat" },
  { name: "Desa", category: "meat" },
  { name: "Salami", category: "meat" },
  { name: "Prošuto", category: "meat" },
  { name: "Bekons", category: "meat" },
  { name: "Cīsiņi", category: "meat" },
  { name: "Pastēte", category: "meat" },
  { name: "Krabju nūjiņas", category: "meat" },
  { name: "Reņģes", category: "meat" },
  { name: "Siļķe", category: "meat" },
  { name: "Anšovi", category: "meat" },
  { name: "Tempe", category: "meat" },
  { name: "Seitāns", category: "meat" },
  { name: "Sojas gaļa", category: "meat" },

  // Veg (Dārzeņi un sēnes)
  { name: "Kartupeļi", category: "veg" },
  { name: "Burkāni", category: "veg" },
  { name: "Sīpoli", category: "veg" },
  { name: "Sarkanie sīpoli", category: "veg" },
  { name: "Puravi", category: "veg" },
  { name: "Ķiploki", category: "veg" },
  { name: "Gurķi", category: "veg" },
  { name: "Tomāti", category: "veg" },
  { name: "Ķiršu tomāti", category: "veg" },
  { name: "Paprika", category: "veg" },
  { name: "Kāposti", category: "veg" },
  { name: "Ziedkāposti", category: "veg" },
  { name: "Brokoļi", category: "veg" },
  { name: "Spināti", category: "veg" },
  { name: "Cukini", category: "veg" },
  { name: "Baklažāni", category: "veg" },
  { name: "Batātes", category: "veg" },
  { name: "Ķirbis", category: "veg" },
  { name: "Bietes", category: "veg" },
  { name: "Ridīsi", category: "veg" },
  { name: "Kāļi", category: "veg" },
  { name: "Selerijas sakne", category: "veg" },
  { name: "Selerijas kāti", category: "veg" },
  { name: "Sparģeļi", category: "veg" },
  { name: "Avokado", category: "veg" },
  { name: "Kukurūza", category: "veg" },
  { name: "Zaļie zirnīši", category: "veg" },
  { name: "Pupiņas", category: "veg" },
  { name: "Lēcas", category: "veg" },
  { name: "Šampinjoni", category: "veg" },
  { name: "Austersēnes", category: "veg" },
  { name: "Baravikas", category: "veg" },
  { name: "Ingvers", category: "veg" },
  { name: "Mārrutki", category: "veg" },
  { name: "Dilles", category: "veg" },
  { name: "Pētersīļi", category: "veg" },
  { name: "Lociņi", category: "veg" },
  { name: "Baziliks", category: "veg" },
  { name: "Koriandrs", category: "veg" },
  { name: "Rukola", category: "veg" },
  { name: "Lapu kāposti (Kale)", category: "veg" },
  { name: "Ledussalāts", category: "veg" },

  // Fruit (Augļi un ogas)
  { name: "Āboli", category: "fruit" },
  { name: "Banāni", category: "fruit" },
  { name: "Apelsīni", category: "fruit" },
  { name: "Citroni", category: "fruit" },
  { name: "Laims", category: "fruit" },
  { name: "Bumbieri", category: "fruit" },
  { name: "Vīnogas", category: "fruit" },
  { name: "Mellenes", category: "fruit" },
  { name: "Zemenes", category: "fruit" },
  { name: "Avenes", category: "fruit" },
  { name: "Dzērvenes", category: "fruit" },
  { name: "Brūklenes", category: "fruit" },
  { name: "Mango", category: "fruit" },
  { name: "Ananāss", category: "fruit" },
  { name: "Greipfrūts", category: "fruit" },
  { name: "Kivi", category: "fruit" },
  { name: "Persiki", category: "fruit" },
  { name: "Nektarīni", category: "fruit" },
  { name: "Plūmes", category: "fruit" },
  { name: "Aprikozes", category: "fruit" },
  { name: "Arbūzs", category: "fruit" },
  { name: "Melone", category: "fruit" },
  { name: "Granātābols", category: "fruit" },
  { name: "Vīģes", category: "fruit" },
  { name: "Dateles", category: "fruit" },
  { name: "Goji ogas", category: "fruit" },

  // Bakery (Maize un konditorija)
  { name: "Maize", category: "bakery" },
  { name: "Baltmaize", category: "bakery" },
  { name: "Rupjmaize", category: "bakery" },
  { name: "Saldskābmaize", category: "bakery" },
  { name: "Graudu maize", category: "bakery" },
  { name: "Sēklu maize", category: "bakery" },
  { name: "Baguette", category: "bakery" },
  { name: "Ciabatta", category: "bakery" },
  { name: "Lavašs", category: "bakery" },
  { name: "Tortiļas", category: "bakery" },
  { name: "Pita", category: "bakery" },
  { name: "Bulciņas", category: "bakery" },
  { name: "Kruasāni", category: "bakery" },
  { name: "Cepumi", category: "bakery" },
  { name: "Kūka", category: "bakery" },
  { name: "Mufini", category: "bakery" },
  { name: "Barankas", category: "bakery" },
  { name: "Kukurūzas sausiņi", category: "bakery" },

  // Dry (Bakaleja, mērces, superprodukti)
  { name: "Rīsi", category: "dry" },
  { name: "Basmati rīsi", category: "dry" },
  { name: "Makaroni", category: "dry" },
  { name: "Spageti", category: "dry" },
  { name: "Griķi", category: "dry" },
  { name: "Kvinoja", category: "dry" },
  { name: "Kuskuss", category: "dry" },
  { name: "Bulgurs", category: "dry" },
  { name: "Milti", category: "dry" },
  { name: "Kviešu milti", category: "dry" },
  { name: "Mandeļu milti", category: "dry" },
  { name: "Kokosriekstu milti", category: "dry" },
  { name: "Turku zirņu milti", category: "dry" },
  { name: "Speltas milti", category: "dry" },
  { name: "Griķu milti", category: "dry" },
  { name: "Kukurūzas milti", category: "dry" },
  { name: "Polenta", category: "dry" },
  { name: "Amarants", category: "dry" },
  { name: "Cukurs", category: "dry" },
  { name: "Brūnais cukurs", category: "dry" },
  { name: "Pūdercukurs", category: "dry" },
  { name: "Agaves sīrups", category: "dry" },
  { name: "Kļavu sīrups", category: "dry" },
  { name: "Rīsu sīrups", category: "dry" },
  { name: "Stēvija", category: "dry" },
  { name: "Eritritols", category: "dry" },
  { name: "Xylitols (Ksilīts)", category: "dry" },
  { name: "Sāls", category: "dry" },
  { name: "Jūras sāls", category: "dry" },
  { name: "Himalaju sāls", category: "dry" },
  { name: "Melnie pipari", category: "dry" },
  { name: "Baltie pipari", category: "dry" },
  { name: "Zaļie pipari", category: "dry" },
  { name: "Rozā pipari", category: "dry" },
  { name: "Smaržīgie pipari", category: "dry" },
  { name: "Kajēnas pipari", category: "dry" },
  { name: "Čili pārslas", category: "dry" },
  { name: "Paprikas pulveris", category: "dry" },
  { name: "Kūpināta paprika", category: "dry" },
  { name: "Kurkuma", category: "dry" },
  { name: "Karijs", category: "dry" },
  { name: "Garam Masala", category: "dry" },
  { name: "Kumīns (Kumin)", category: "dry" },
  { name: "Kimenes", category: "dry" },
  { name: "Koriandra sēklas", category: "dry" },
  { name: "Sinepju sēklas", category: "dry" },
  { name: "Lauru lapas", category: "dry" },
  { name: "Raudene (Oregano)", category: "dry" },
  { name: "Baziliks (kaltēts)", category: "dry" },
  { name: "Timiāns", category: "dry" },
  { name: "Rozmarīns", category: "dry" },
  { name: "Salvija", category: "dry" },
  { name: "Majorāns", category: "dry" },
  { name: "Estragons", category: "dry" },
  { name: "Dilles (kaltētas)", category: "dry" },
  { name: "Pētersīļi (kaltēti)", category: "dry" },
  { name: "Provansas garšaugi", category: "dry" },
  { name: "Itāļu garšaugi", category: "dry" },
  { name: "Krustnagliņas", category: "dry" },
  { name: "Muskatrieksts", category: "dry" },
  { name: "Kardamons", category: "dry" },
  { name: "Zvaigžņu anīss", category: "dry" },
  { name: "Vaniļas cukurs", category: "dry" },
  { name: "Vaniļas ekstrakts", category: "dry" },
  { name: "Vaniļas pāksts", category: "dry" },
  { name: "Kanēlis", category: "dry" },
  { name: "Kanēļa standziņas", category: "dry" },
  { name: "Ingvers (pulveris)", category: "dry" },
  { name: "Safrāns", category: "dry" },
  { name: "Sumaks", category: "dry" },
  { name: "Adžika", category: "dry" },
  { name: "Olīveļļa", category: "dry" },
  { name: "Saulespuķu eļļa", category: "dry" },
  { name: "Sezama eļļa", category: "dry" },
  { name: "Zivju mērce", category: "dry" },
  { name: "Austeru mērce", category: "dry" },
  { name: "Sojas mērce", category: "dry" },
  { name: "Teriyaki mērce", category: "dry" },
  { name: "Vusteras mērce", category: "dry" },
  { name: "Rīsu etiķis", category: "dry" },
  { name: "Vīna etiķis", category: "dry" },
  { name: "Balzāmetiķis", category: "dry" },
  { name: "Tahini", category: "dry" },
  { name: "Melnā tahini pasta", category: "dry" },
  { name: "Miso pasta (baltā)", category: "dry" },
  { name: "Miso pasta (tumšā)", category: "dry" },
  { name: "Karija pasta (zaļā)", category: "dry" },
  { name: "Karija pasta (sarkanā)", category: "dry" },
  { name: "Harisa", category: "dry" },
  { name: "Sriracha mērce", category: "dry" },
  { name: "Pesto (Genoese)", category: "dry" },
  { name: "Pesto (Sarkanais)", category: "dry" },
  { name: "Wasabi", category: "dry" },
  { name: "Taco garšvielas", category: "dry" },
  { name: "Olīvas", category: "dry" },
  { name: "Kaperi", category: "dry" },
  { name: "Tomātu mērce", category: "dry" },
  { name: "Kečups", category: "dry" },
  { name: "Majonēze", category: "dry" },
  { name: "Sinepes", category: "dry" },
  { name: "Buljona kubiņi", category: "dry" },
  { name: "Kaltēti sīpoli", category: "dry" },
  { name: "Kaltēti ķiploki", category: "dry" },
  { name: "Sinepju pulveris", category: "dry" },
  { name: "Sēnes (kaltētas)", category: "dry" },
  { name: "Saulē kaltēti tomāti", category: "dry" },
  { name: "Auzas", category: "dry" },
  { name: "Auzu pārslas", category: "dry" },
  { name: "Kafija", category: "dry" },
  { name: "Kafijas pupiņas", category: "dry" },
  { name: "Tēja", category: "dry" },
  { name: "Sojas granulas", category: "dry" },
  { name: "Uztura raugs", category: "dry" },
  { name: "Spirulīnas pulveris", category: "dry" },
  { name: "Hlorellas pulveris", category: "dry" },
  { name: "Nori lapas", category: "dry" },
  { name: "Wakame jūraszāles", category: "dry" },
  { name: "Proteīna pulveris", category: "dry" },
  { name: "Humuss", category: "dry" },

  // Nuts, Seeds & Fiber (Rieksti, sēklas un šķiedrvielas)
  { name: "Čia sēklas", category: "dry" },
  { name: "Linsēklas", category: "dry" },
  { name: "Maltas linsēklas", category: "dry" },
  { name: "Saulespuķu sēklas", category: "dry" },
  { name: "Ķirbju sēklas", category: "dry" },
  { name: "Kaņepju sēklas", category: "dry" },
  { name: "Sezama sēklas", category: "dry" },
  { name: "Melnā sezama sēklas", category: "dry" },
  { name: "Magones", category: "dry" },
  { name: "Valrieksti", category: "dry" },
  { name: "Lazdu rieksti", category: "dry" },
  { name: "Indijas rieksti", category: "dry" },
  { name: "Mandeļu rieksti", category: "dry" },
  { name: "Mandeļu skaidiņas", category: "dry" },
  { name: "Pistācijas", category: "dry" },
  { name: "Brazīlijas rieksti", category: "dry" },
  { name: "Pekanrieksti", category: "dry" },
  { name: "Makadamijas rieksti", category: "dry" },
  { name: "Ciedru rieksti", category: "dry" },
  { name: "Zemesrieksti", category: "dry" },
  { name: "Zemesriekstu sviests", category: "dry" },
  { name: "Mandeļu sviests", category: "dry" },
  { name: "Indijas riekstu sviests", category: "dry" },
  { name: "Kviešu klijas", category: "dry" },
  { name: "Auzu klijas", category: "dry" },
  { name: "Psilliums (Psyllium)", category: "dry" },
  { name: "Šķiedrvielu maisījums", category: "dry" },

  // Kids (Bērnu pārtika)
  { name: "Bērnu biezenis (augļu)", category: "other" },
  { name: "Bērnu biezenis (dārzeņu)", category: "other" },
  { name: "Bērnu biezenis (gaļas)", category: "other" },
  { name: "Bērnu putriņa", category: "other" },
  { name: "Rīsu putra bērniem", category: "other" },
  { name: "Auzu putra bērniem", category: "other" },
  { name: "Kukurūzas nūjiņas", category: "sweets" },
  { name: "Bērnu cepumi", category: "sweets" },
  { name: "Piena maisījums", category: "dairy" },
  { name: "Bērnu tēja", category: "drinks" },
  { name: "Bērnu sula", category: "drinks" },
  { name: "Biezpiena sieriņš", category: "dairy" },
  { name: "Jogurts bērniem", category: "dairy" },
  { name: "Bērnu galetiņas", category: "bakery" },
  { name: "Bērnu makaroni (formas)", category: "dry" },
  { name: "Augļu batoniņš (bērnu)", category: "sweets" },
  { name: "Putraimi", category: "dry" },

  // Frozen (Saldēti)
  { name: "Saldēti dārzeņi", category: "frozen" },
  { name: "Saldēti zirnīši", category: "frozen" },
  { name: "Saldētas pākšu pupiņas", category: "frozen" },
  { name: "Saldējums", category: "frozen" },
  { name: "Pelmeņi", category: "frozen" },
  { name: "Saldētas ogas", category: "frozen" },
  { name: "Saldētas zemenes", category: "frozen" },
  { name: "Saldētas picas", category: "frozen" },
  { name: "Saldēti frī kartupeļi", category: "frozen" },
  { name: "Saldēta mīkla", category: "frozen" },
  { name: "Falafeli", category: "frozen" },

  // Drinks (Dzērieni)
  { name: "Ūdens", category: "drinks" },
  { name: "Gāzēts ūdens", category: "drinks" },
  { name: "Sula", category: "drinks" },
  { name: "Apelsīnu sula", category: "drinks" },
  { name: "Ābolu sula", category: "drinks" },
  { name: "Tomātu sula", category: "drinks" },
  { name: "Vīns", category: "drinks" },
  { name: "Sarkanais vīns", category: "drinks" },
  { name: "Baltais vīns", category: "drinks" },
  { name: "Alus", category: "drinks" },
  { name: "Sidrs", category: "drinks" },
  { name: "Prosecco", category: "drinks" },
  { name: "Kombuča", category: "drinks" },
  { name: "Limonāde", category: "drinks" },
  { name: "Kvass", category: "drinks" },

  // Sweets & Snacks (Saldumi un uzkodas)
  { name: "Šokolāde", category: "sweets" },
  { name: "Melnā šokolāde", category: "sweets" },
  { name: "Piena šokolāde", category: "sweets" },
  { name: "Konfektes", category: "sweets" },
  { name: "Ievārījums", category: "sweets" },
  { name: "Zefīrs", category: "sweets" },
  { name: "Halva", category: "sweets" },
  { name: "Čipsi", category: "sweets" },
  { name: "Popkorns", category: "sweets" },
  { name: "Sāļie riekstiņi", category: "sweets" },
  { name: "Žāvēti augļi", category: "sweets" },
  { name: "Kakao pupiņas", category: "sweets" },
  { name: "Žāvētas dzērvenes", category: "sweets" },
  { name: "Žāvētas aprikozes", category: "sweets" },
  { name: "Žāvētas plūmes", category: "sweets" },
  { name: "Rozīnes", category: "sweets" },
  { name: "Proteīna batoniņš", category: "sweets" },
];

export function getCategoryByProductName(name: string): KitchenCategory {
  const normalized = name.toLowerCase().trim();
  const match = PRODUCT_DICTIONARY.find(p => normalized.includes(p.name.toLowerCase()));
  return match ? match.category : "other";
}

export function getSuggestions(query: string): ProductSuggestion[] {
  if (!query || query.length < 2) return [];
  const normalized = query.toLowerCase();
  return PRODUCT_DICTIONARY.filter(p => p.name.toLowerCase().includes(normalized)).slice(0, 5);
}
